### ISSUE TITLE
sass-lint does not support property-sort-order with custom properties

### ISSUE THREAD

**Issue by c4rlosviteri** [verndale/toolkit#27]
The following code is not supported by sass-lint:

```css
:root {
  --red: #ff0000;
}
```
It throws this error:
![image](https://user-images.githubusercontent.com/1807897/120151562-052b5f00-c1b2-11eb-826a-026c7d24f8c7.png)
